// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBowbPuWVKcOBrkB90WJVwVSkwcLMTYeo',
    appId: '1:103286660483:web:663cf3fb4b91cbc790aab6',
    messagingSenderId: '103286660483',
    projectId: 'eb-task',
    authDomain: 'eb-task.firebaseapp.com',
    storageBucket: 'eb-task.firebasestorage.app',
    measurementId: 'G-7Q1G7V7BSC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAd_WWDEQNrgj_DvY_zZdA89_Cg9iGYj8A',
    appId: '1:103286660483:android:5f1fce3500b72fbf90aab6',
    messagingSenderId: '103286660483',
    projectId: 'eb-task',
    storageBucket: 'eb-task.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcN6YQ3xVH0KgwoUloMugAp6iWVbzJMZc',
    appId: '1:103286660483:ios:bbf90bf37d72078090aab6',
    messagingSenderId: '103286660483',
    projectId: 'eb-task',
    storageBucket: 'eb-task.firebasestorage.app',
    iosBundleId: 'com.example.ebTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcN6YQ3xVH0KgwoUloMugAp6iWVbzJMZc',
    appId: '1:103286660483:ios:bbf90bf37d72078090aab6',
    messagingSenderId: '103286660483',
    projectId: 'eb-task',
    storageBucket: 'eb-task.firebasestorage.app',
    iosBundleId: 'com.example.ebTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBowbPuWVKcOBrkB90WJVwVSkwcLMTYeo',
    appId: '1:103286660483:web:9663217e109eb30390aab6',
    messagingSenderId: '103286660483',
    projectId: 'eb-task',
    authDomain: 'eb-task.firebaseapp.com',
    storageBucket: 'eb-task.firebasestorage.app',
    measurementId: 'G-CFL6B57ZQT',
  );
}
